# Generated by Django 4.2.1 on 2023-06-28 18:21

from django.db import migrations, models
import django.db.models.deletion
import emotion_recognizer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(unique=True, upload_to=emotion_recognizer.models.get_upload_to)),
                ('user_id', models.BigIntegerField(unique=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
