# Generated by Django 4.2.2 on 2023-07-25 05:51

from django.db import migrations, models
import emotion_recognizer.models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_recognizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_upload',
            field=models.FileField(upload_to=emotion_recognizer.models.get_upload_to),
        ),
    ]
